title: Principles of Surf Contest Simulation
description: Official Manual of Surf Contest Simulation, in Association with The Contest Simulator

markdown: kramdown

remote_theme: just-the-docs/just-the-docs  # pin for reproducibility: just-the-docs/just-the-docs@v0.6.3

plugins:
  - jekyll-remote-theme

just_the_docs:
  toc:
    enabled: true
    min_level: 2
    max_level: 3
  search_enabled: true

color_scheme: light
