title: Principles of Surf Contest Simulation
description: Official Manual of Surf Contest Simulation, in Association with The Contest Simulator
url: https://iarxm.github.io/csim-man
repository: iarxm/csim-man
base-url csim-man

theme: just-the-docs

markdown: kramdown

just_the_docs:
  toc:
    enabled: true
    min_level: 2
    max_level: 3
  search_enabled: true

color_scheme: light


#remote_theme: just-the-docs/just-the-docs  # pin for reproducibility: just-the-docs/just-the-docs@v0.6.3
#
#plugins:
#  - jekyll-remote-theme

