title: Principles of Surf Contest Simulation
description: Official manual of surf contest simulation as implemented in the contest simulator

markdown: kramdown

remote_theme: just-the-docs
color_scheme: light
just_the_docs:
  toc:
    enabled: true
    min_level: 2
    max_level: 3

