title: Surf Games - Simulation Training
description: Official Manual of Simulation Training for The Surf Games. To be used with The Contest Simulator App or some equivalent digitalized scoring system.
url: https://iarxm.github.io/csim-man
repository: iarxm/csim-man
base-url: csim-man

theme: jekyll-theme-minimal

markdown: kramdown

#theme: just-the-docs
#just_the_docs:
#  toc:
#    enabled: true
#    min_level: 1
#    max_level: 4
#  search_enabled: true

#color_scheme: light


#remote_theme: just-the-docs/just-the-docs  # pin for reproducibility: just-the-docs/just-the-docs@v0.6.3
#
#plugins:
#  - jekyll-remote-theme

