title: Principles of Surf Contest Simulation
description: Official Manual of Surf Contest Simulation, in Association with The Contest Simulator

markdown: kramdown

theme: just-the-docs
color_scheme: light
just_the_docs:
  toc:
    enabled: true
    min_level: 2
    max_level: 3

