title: Principles of Surf Contest Simulation
description: Official manual of surf contest simulation as implemented in the contest simulator
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal

#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minima
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine

markdown: kramdown

remote_theme: just-the-docs
color_scheme: light
# Optional: enable the table of contents sidebar
# This will auto-index all headings on the page
just_the_docs:
  toc:
    enabled: true
    min_level: 2
    max_level: 3
