name: Build & Deploy (Just the Docs - remote_theme)

on:
  push:
    branches: [main]

permissions:
  contents: write   # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install deps
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build -d _site --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
